### ISSUE TITLE
I cannot import maven project

### ISSUE THREAD

**Issue by 14841484** [matsim-vsp/drt-speed-up#7]
Hi.

I have a problem about import of pom.xml.
Please look at the below.
I have not changed pom.xml but I get this error.

What should I do?
@michalmac ,please teach me about this.

explanation	　　　　　　　　　　　　　resoarce pass          　　　　location	　　　　　　　type
Missing artifact jgridshift:jgridshift:jar:1.0	pom.xml	　　　　　　　　/drt-speed-up	line1	Maven 依存関係問題
Missing artifact junit:junit:jar:4.12	                pom.xml	                             /drt-speed-up	line 1	Maven 依存関係問題
Missing artifact org.hamcrest:hamcrest-core:jar:1.3	pom.xml	             /drt-speed-up	line 1	Maven 依存関係問題
Missing artifact org.matsim:matsim:jar:13.0-2020w41-SNAPSHOT	pom.xml	            /drt-speed-up	行line1	Maven 依存関係問題
Missing artifact org.matsim:matsim:jar:tests:13.0-2020w41-SNAPSHOT	pom.xml	/drt-speed-up	line1	Maven 依存関係問題
Missing artifact org.matsim:matsim-examples:jar:13.0-2020w41-SNAPSHOT	pom.xml	/drt-speed-up	line1	Maven 依存関係問題
Missing artifact org.matsim.contrib:av:jar:13.0-2020w41-SNAPSHOT	pom.xml	/drt-speed-up	line1	Maven 依存関係問題
Missing artifact org.matsim.contrib:drt:jar:13.0-2020w41-SNAPSHOT	pom.xml	/drt-speed-up	line1	Maven 依存関係問題
Missing artifact org.matsim.contrib:dvrp:jar:13.0-2020w41-SNAPSHOT	pom.xml	/drt-speed-up	line1	Maven 依存関係問題

**Comment by michalmac** [comment]
This is an old repository. You will find the most up-to-date drt-speed-up functionality here: https://github.com/matsim-org/matsim-libs/tree/master/contribs/drt/src/main/java/org/matsim/contrib/drt/speedup (that is inside the DRT contrib of matsim-libs)
